name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest # Указан Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Perform Go Mod Tidy for all modules
        # Запускаем go mod tidy для каждого модуля, чтобы разрешить зависимости
        # forward slashes используются для paths даже на Windows
        run: |
          go mod tidy -C ./goldentest
          go mod tidy -C ./translator
          go mod tidy -C ./machine
          go mod tidy -C ./isa

      - name: Set up Go workspace (go.work)
        # Запускаем go work sync из корневой директории, где находится go.work
        # working-directory не нужен, если команда выполняется из корня репозитория
        run: go work sync

      - name: Run tests in goldentest module
        working-directory: ./goldentest # Указываем путь к модулю goldentest
        run: go test -v ./