name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Perform Go Mod Tidy for all modules
        run: |
          go mod tidy -C ./goldentest
          go mod tidy -C ./translator
          go mod tidy -C ./machine
          go mod tidy -C ./isa

      - name: Build machine module
        working-directory: ./machine
        run: go build -o machine

      - name: Set execute permissions for machine
        working-directory: ./machine
        run: chmod +x machine

      - name: Build translator module
        working-directory: ./translator
        run: go build -o translator

      - name: Set execute permissions for translator
        working-directory: ./translator
        run: chmod +x translator

      - name: Set up Go workspace (go.work)
        run: go work sync

      - name: Go fmt/imports check
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          if ! goimports -l .; then
            echo "::error file=.::Go files not formatted with goimports or imports are unorganized. Please run 'goimports -w .' on your local machine."
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: ./isa ./translator ./machine ./goldentest --config=./.golangci.yml -v


      - name: Run tests in goldentest module
        working-directory: ./goldentest # Указываем путь к модулю goldentest
        run: go test -v ./