name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Set up Go workspace (go.work)
        run: go work sync

      - name: Format check (gofmt)
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          if ! goimports -l .; then
            echo "::error file=.::Go files not formatted with goimports or imports are unorganized. Please run 'goimports -w .' on your local machine."
            exit 1
          fi

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run tests in goldentest module
        working-directory: goldentest
        run: go test -v ./...
